In [126]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder



In [127]:
data =pd.read_csv('insurance.csv', index_col=0)
data

sex     bmi  children smoker     region      charges
age                                                         
19   female  27.900         0    yes  southwest  16884.92400
18     male  33.770         1     no  southeast   1725.55230
28     male  33.000         3     no  southeast   4449.46200
33     male  22.705         0     no  northwest  21984.47061
32     male  28.880         0     no  northwest   3866.85520
..      ...     ...       ...    ...        ...          ...
50     male  30.970         3     no  northwest  10600.54830
18   female  31.920         0     no  northeast   2205.98080
18   female  36.850         0     no  southeast   1629.83350
21   female  25.800         0     no  southwest   2007.94500
61   female  29.070         0    yes  northwest  29141.36030

[1338 rows x 6 columns]

In [157]:
data.isnull().sum()

sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [128]:

import numpy as np
le = LabelEncoder()
data['sex'] = le.fit_transform(data['sex'])
print(data)

le=LabelEncoder()
data['smoker']=le.fit_transform(data['smoker'])
print(data)

le=LabelEncoder()
data['region']=le.fit_transform(data['region'])
print(data)


     sex     bmi  children smoker     region      charges
age                                                      
19     0  27.900         0    yes  southwest  16884.92400
18     1  33.770         1     no  southeast   1725.55230
28     1  33.000         3     no  southeast   4449.46200
33     1  22.705         0     no  northwest  21984.47061
32     1  28.880         0     no  northwest   3866.85520
..   ...     ...       ...    ...        ...          ...
50     1  30.970         3     no  northwest  10600.54830
18     0  31.920         0     no  northeast   2205.98080
18     0  36.850         0     no  southeast   1629.83350
21     0  25.800         0     no  southwest   2007.94500
61     0  29.070         0    yes  northwest  29141.36030

[1338 rows x 6 columns]
     sex     bmi  children  smoker     region      charges
age                                                       
19     0  27.900         0       1  southwest  16884.92400
18     1  33.770         1       0  southeas

In [129]:
#X = data.drop('charges', axis=1)
X=data['smoker']
y = data['charges']

In [130]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

#split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=123)



In [131]:
#build model
from sklearn.neighbors import KNeighborsRegressor
model=KNeighborsRegressor()

In [132]:
#training model
X_train = np.reshape(X_train, (-1, 1))
model.fit(X_train, y_train)

KNeighborsRegressor()

In [133]:
# prediction result
#y_pred = model.predict(X_test)
#y_pred
import numpy as np

# Reshape X_test to 2D array
X_test = np.reshape(X_test, (X_test.shape[0], -1))

# Perform prediction
y_pred = model.predict(X_test)



In [134]:
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error,r2_score

# Model evaluation
mape = mean_absolute_percentage_error(y_test, y_pred)
print('MAPE: {}'.format(str(mape)))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print('RMSE: {}'.format(str(rmse)))
r2 = r2_score(y_test, y_pred)
print('R-squared: {}'.format(str(r2)))


MAPE: 0.546455622894961
RMSE: 8277.886999862576
R-squared: 0.5518285948789599


In [143]:
# Model build 2
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [144]:
model.fit(X_train, y_train)


LinearRegression()

In [137]:
y_pred = model.predict(X_test)
y_pred

array([ 8505.41551562,  8505.41551562, 31924.62635285,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562, 31924.62635285,  8505.41551562, 31924.62635285,
        8505.41551562,  8505.41551562, 31924.62635285, 31924.62635285,
       31924.62635285, 31924.62635285,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562, 31924.62635285,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
       31924.62635285,  8505.41551562,  8505.41551562,  8505.41551562,
      

In [145]:
# Model evaluation
mape = mean_absolute_percentage_error(y_test, y_pred)
print('MAPE: {}'.format(str(mape)))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print('RMSE: {}'.format(str(rmse)))
r2 = r2_score(y_test, y_pred)
print('R-squared: {}'.format(str(r2)))

MAPE: 0.9056454423532044
RMSE: 12919.522734107175
R-squared: -0.09168689607001346


In [146]:
# build model 3
from sklearn.svm import SVR
model = SVR()

In [140]:
# Training model
model.fit(X_train, y_train)


SVR()

In [141]:
# Prediction result
y_pred = model.predict(X_test)
y_pred

array([9303.29772499, 9303.29772499, 9730.47149062, 9303.29772499,
       9303.29772499, 9303.29772499, 9303.29772499, 9303.29772499,
       9303.29772499, 9303.29772499, 9303.29772499, 9303.29772499,
       9303.29772499, 9730.47149062, 9303.29772499, 9730.47149062,
       9303.29772499, 9303.29772499, 9730.47149062, 9730.47149062,
       9730.47149062, 9730.47149062, 9303.29772499, 9303.29772499,
       9303.29772499, 9303.29772499, 9303.29772499, 9303.29772499,
       9303.29772499, 9303.29772499, 9303.29772499, 9303.29772499,
       9303.29772499, 9303.29772499, 9303.29772499, 9303.29772499,
       9303.29772499, 9303.29772499, 9303.29772499, 9303.29772499,
       9303.29772499, 9303.29772499, 9303.29772499, 9730.47149062,
       9303.29772499, 9303.29772499, 9303.29772499, 9303.29772499,
       9303.29772499, 9303.29772499, 9303.29772499, 9303.29772499,
       9730.47149062, 9303.29772499, 9303.29772499, 9303.29772499,
       9730.47149062, 9730.47149062, 9730.47149062, 9303.29772

In [142]:
# Model evaluation
mape = mean_absolute_percentage_error(y_test, y_pred)
print('MAPE: {}'.format(str(mape)))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print('RMSE: {}'.format(str(rmse)))
r2 = r2_score(y_test, y_pred)
print('R-squared: {}'.format(str(r2)))

MAPE: 0.9056454423532044
RMSE: 12919.522734107175
R-squared: -0.09168689607001346


In [149]:
#built model 4
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(X_train, y_train)


DecisionTreeRegressor()

In [150]:
# Prediction result
y_pred = model.predict(X_test)
y_pred

array([ 8505.41551562,  8505.41551562, 31924.62635285,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562, 31924.62635285,  8505.41551562, 31924.62635285,
        8505.41551562,  8505.41551562, 31924.62635285, 31924.62635285,
       31924.62635285, 31924.62635285,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562, 31924.62635285,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
        8505.41551562,  8505.41551562,  8505.41551562,  8505.41551562,
       31924.62635285,  8505.41551562,  8505.41551562,  8505.41551562,
      

In [151]:
# Model evaluation
mape = mean_absolute_percentage_error(y_test, y_pred)
print('MAPE: {}'.format(str(mape)))
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print('RMSE: {}'.format(str(rmse)))
r2 = r2_score(y_test, y_pred)
print('R-squared: {}'.format(str(r2)))

MAPE: 0.7681023133764814
RMSE: 7070.344661897021
R-squared: 0.6730462472240666
